YT_Movies/YTM_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.homePage, name='homePage'),
    path('signup/', views.signupPage, name='signupPage'),
    path('login/', views.loginPage, name='loginPage'),
    path('logout/', views.logoutUser, name='logoutPage'),
    path('all/', views.allPage, name='allPage'),
    path('top/', views.topPage, name='topPage'),
    path('all/<slug:slug>/', views.allPage, name='filterPage'),
    path('movie/<int:pk>/', views.moviePage, name='moviePage'),

]

YT_Movies/YT_Movies/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('YTM_app.urls')),
]

YT_Movies/YTM_app/models.py
from django.db import models
from pytils.translit import slugify

# Create your models here.

class Genre (models.Model):
    genreName = models.CharField("Genre", max_length=50, null=True, blank=True)
    slug = models.SlugField(unique=True, blank=True, editable=False)

    def __str__(self):
        return self.genreName
    
    def save(self, *args, **kwargs):
        self.slug = slugify(self.genreName)
        super().save(*args, **kwargs)

class Actor(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class Character(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class Movie(models.Model):
    movieName = models.CharField("Movie name", max_length=255, null=True, blank=True)
    year = models.IntegerField("Year", null=True, blank=True)
    producer = models.CharField("Producer", max_length=255, null=True, blank=True)
    description = models.TextField("Description", null=True, blank=True)
    poster = models.CharField("Poster URL", max_length=500, null=True, blank=True)
    movieLink = models.CharField("Movie URL", max_length=500, null=True, blank=True)
    rating = models.FloatField("Rating", default=1.0, null=True, blank=True)
    genres = models.ManyToManyField(Genre)
    screenshots = models.ManyToManyField('Screenshot', blank=True)
    actors = models.ManyToManyField(Actor, through='Role')
    isTopTen = models.BooleanField("Top 10", default=False, null=True, blank=True)
    isRecommended = models.BooleanField("Recommended", default=False, null=True, blank=True)

    def __str__(self):
        return self.movieName
    
class Screenshot(models.Model):
    movieFrom = models.ForeignKey(Movie, default='', on_delete=models.CASCADE)
    img = models.CharField("URL", default='', max_length=255, null=True, blank=True)
    altText = models.CharField("Alternative Text", default='', max_length=255, null=True, blank=True)

    def __str__(self):
        return f"{self.pk}) {self.movieFrom.movieName}"
    
class Role(models.Model):
    actor = models.ForeignKey(Actor, on_delete=models.CASCADE)
    character = models.ForeignKey(Character, on_delete=models.CASCADE)
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.actor} as {self.character} in {self.movie}"

YT_Movies/YTM_app/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class NewUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username','first_name', 'last_name', 'email', 'password1', 'password2')

YT_Movies/YTM_app/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Movie, Genre
from .forms import NewUserForm
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, authenticate, logout
from django.db.models import Q

# Create your views here.
def homePage(request):
    return render(request, "primaryFrontend/index.html")

def allPage(request, slug=None):
    genre = None
    movies = Movie.objects.all()
    genres = Genre.objects.order_by('genreName')
    searchData = request.GET.get('search')
    if searchData:
        movies = Movie.objects.filter(Q(movieName__icontains = searchData))
    if slug:
        genre = get_object_or_404(Genre, slug=slug)
        movies = movies.filter(genres__in=[genre])
    return render(request, "primaryFrontend/all.html", {
        'movies': movies,
        'genres': genres,
        'genre': genre
    })
    
def moviePage(request, pk):
    movie = get_object_or_404(Movie, pk=pk)
    return render(request, "primaryFrontend/movie.html", {
        'movie': movie
    })

def topPage(request):
    rMovie = Movie.objects.all()[:1]
    topMovies = Movie.objects.all()[:10]
    return render(request, "primaryFrontend/top.html",{
        'rMovie': rMovie,
        'topMovies': topMovies
    })

def signupPage(request):
    if request.method == "POST":
        form = NewUserForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("loginPage")
    else:
        form = NewUserForm()

    return render(request, "user/signup.html", {
        'form': form
    }) 

def loginPage(request):
    if request.method == "POST":
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                redirect("allPage")

    else:
        form = AuthenticationForm()

    return render(request, "user/login.html", {
        'form': form
    })

def logoutUser(request):
    logout(request)
    return redirect("homePage")

YT_Movies/YTM_app/templates/base.html
{% load static %}
{% comment %} {% load bootstrap5 %} {% endcomment %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static './css/style.css' %}">
    <link rel="stylesheet" href="{% static './css/bs.min.css' %}">
    {% comment %} {% bootstrap_css %} {% endcomment %}
       
    {% block style %}
    {% endblock %}
</head>

<body>
    <!-- Navbar -->
    <nav class="navbar navbar-expand-sm bg-dark">
        <div class="container-lg">
            <a class="navbar-brand text-light" href="{% url 'homePage' %}">Youtube Movies</a>
            <form class="d-flex my-auto mx-3" role="search">
                <input class="form-control me-2 " type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
            <div class="collapse navbar-collapse">
                <div class="navbar-nav ms-auto">
                    <a class="nav-link text-light" href="{% url 'allPage' %}">All Movies</a>                    
                    <a class="nav-link text-light" href="{% url 'topPage' %}">Top Movies</a>                    
                    {% if user.is_authenticated %}
                    <a class="nav-link text-light" href="{% url 'logoutPage' %}">{{ user.username }}</a>
                    {% else %}
                    <a class="nav-link text-light" href="{% url 'signupPage' %}">Sign Up</a>
                    <a class="nav-link text-light" href="{% url 'loginPage' %}">Log In</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </nav>

    {% block content %}
    {% endblock %}


    <script src="{% static './js/bs.min.js' %}"></script>
    {% comment %} {% bootstrap_javascript %} {% endcomment %}
    <script src="{% static './js/jquery-3.6.4.min.js' %}"></script>
    <script src="{% static './js/owl.carousel.min.js' %}"></script>
    <script src="{% static './js/carousel.js' %}"></script>
</body>

</html>

YT_Movies/YTM_app/templates/primaryFrontend/all.html
{% extends '../base.html' %}
{% load static %}

{% block title %}Search - Youtube Movies{% endblock title %}

{% block style %}
<link rel="stylesheet" href="{% static './css/mvcards.css' %}">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css" integrity="sha512-SzlrxWUlpfuzQ+pcUCosxcglQRNAq/DZjVsC0lE40xsADsfeQoEypE+enwcOiGjk/bSuGGKHEyjSoQ1zVisanQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
{% endblock style %}

{% block content %}
<div class="container-lg my-5 py-4">
    <div class="row">
        <div class="col-3" id="params">
            <!-- Search Params -->
            <div class="card">
                <div class="card-header">
                    Search Terms
                </div>
                <form action="{% url 'allPage' %}" role="search" class="mb-0">
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item d-flex">
                            <input class="form-control" type="search" name="search" placeholder="Search" aria-label="Search">
                        </li>
                        <li class="list-group-item">
                            <h5>Genres</h5>
                            <ul style="list-style-type: none">
                                {% for genre in genres %}
                                <li>    
                                    <a href="{% url 'filterPage' slug=genre.slug %}">{{ genre.genreName }}</a>
                                </li>
                                {% endfor %}
                            </ul>
                        </li>
                        <li class="list-group-item d-flex" style="justify-content: space-evenly;">
                            <a href="{% url 'allPage' %}" role="button" class="btn btn-outline-danger">Reset</a>
                            <button class="btn btn-outline-success" type="submit">Search</button>
                        </li>
                    </ul>
                </form>
            </div>
        </div>
        <div class="col-9">
            <div class="grid">
                {% for movie in movies %}
                <a class="card text-bg-dark" href="{% url 'moviePage' pk=movie.pk %}">
                    <img src="{{ movie.poster }}" class="card-img " alt="...">
                    <div class="card-img-overlay d-flex flex-column">
                        <h4 class="card-title">{{ movie.movieName }}</h4>
                        <p class="card-text desc">{{ movie.description }}</p>
                        <p class="card-text"><small>
                            {% for genre in movie.genres.all %}
                                {{ genre.genreName }}, 
                            {% endfor %}
                        </small></p>
                    </div>
                </a>
                {% endfor %}
            </div>
        </div>
    </div>
</div>
{% endblock content %}

YT_Movies/YTM_app/templates/primaryFrontend/index.html
{% extends '../base.html' %}
{% load static %}

{% block title %}YouTube Movies{% endblock title %}

{% block style %}
<style>
    body{
        background: linear-gradient(#000000a0, #000000a0), url({% static './img/background.jpg' %});
        background-repeat: repeat;
        background-position: center;
        background-size: cover;
    }
</style>
{% endblock style %}

{% block content %}
<div class="banner">
    <div class="container text-light d-flex">

        <!-- Show Example Movie -->
        <img class="poster me-4" src="https://m.media-amazon.com/images/M/MV5BN2RhZDBhMmMtYjFjNi00YWVjLTllZDEtZjA3MjY0NjhkZDAwXkEyXkFqcGdeQXVyMTA2MTU3NDk1._V1_.jpg" alt="">
        <div class="my-auto">

            <h1>Movie Title</h1>
            <p>Labore ex labore Lorem officia nostrud. Dolor excepteur sunt aute magna occaecat dolore ad qui dolor enim ipsum aute. Ea officia adipisicing tempor Lorem consequat voluptate non eiusmod officia. Elit minim voluptate labore sit occaecat in commodo. Officia sit consequat pariatur in Lorem occaecat in nostrud fugiat laboris. Veniam ut nisi et do deserunt Lorem aliquip aliquip tempor nisi. Ullamco officia consequat aute occaecat nostrud magna labore consequat ut elit veniam anim id nostrud.</p>
            
            <!-- Buttons -->
            <h4>Watch this and other original movies from YouTube Content Creators</h4>
            <a role="button" class="btn btn-danger me-2" href="{% url 'moviePage' pk=1 %}">Watch</a>
            <a role="button" class="btn btn-primary" href="{% url 'allPage' %}">All Movies</a>
        </div>
        
    </div>
</div>
{% endblock content %}

YT_Movies/YTM_app/templates/primaryFrontend/movie.html
{% extends '../base.html' %}
{% load static %}

{% block title %}MovieName - YouTube Movies{% endblock title %}

{% block style %}
    <link rel="stylesheet" href="{% static './css/movie-grid.css' %}">
    <link rel="stylesheet" href="{% static './css/mvcards.css' %}">
    <link rel="stylesheet" href="{% static './css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static './css/owl.theme.default.min.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css" integrity="sha512-SzlrxWUlpfuzQ+pcUCosxcglQRNAq/DZjVsC0lE40xsADsfeQoEypE+enwcOiGjk/bSuGGKHEyjSoQ1zVisanQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
{% endblock style %}

{% block content %}
<main class="container d-flex flex-column">
    <div class="my-4 grid">
        <div class="poster">
            <img src="{{ movie.poster }}" alt="">
        </div>
        <h1 class="title">{{ movie.movieName }}</h1>
        <p class="desc">{{ movie.description }}</p>
        <div class="genres">
            <p><b>Genres:</b> 
            {% for genre in movie.genres.all %}
                {{ genre.genreName }},
            {% endfor %}
            </p>
        </div>
        <div class="rating">
            <p><b>Rating:</b> {{ movie.rating }}</p>
        </div>
        <div class="actor">
            <h4>Actors</h4>
            <ul>
                {% for role in movie.role_set.all %}
                <li><b>{{ role.actor }}</b> as {{ role.character }}</li>
                {% endfor %}
            </ul>
        </div>
        <div class="date">
            <p><b>Year:</b> {{ movie.year }}</p>
        </div>
        <div class="producer">
            <p><b>Producer:</b> {{ movie.producer }}</p>
        </div>
        <div class="screenshots">
            <div class="owl-carousel owl-theme">
                {% for screenshot in movie.screenshots.all %}
                <img src="{{ screenshot.img }}" alt="{{ screenshot.altText }}">
                {% endfor %}
            </div>
            <div class="custom-nav mt-2">
                <div class="owl-dots"></div> <!-- Navigation dots -->
                <div class="owl-nav">
                    <button class="owl-prev"><i class="fas fa-chevron-left"></i></button> <!-- Prev button -->
                    <button class="owl-next"><i class="fas fa-chevron-right"></i></button> <!-- Next button -->
                </div>
            </div>
        </div>
    </div>

    <iframe width="720" height="405" src="https://www.youtube-nocookie.com/embed/{{ movie.movieLink }}"
        title="YouTube video player" frameborder="0"
        allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
        allowfullscreen class="mx-auto my-4"></iframe>
</main>
{% endblock content %}

YT_Movies/YTM_app/templates/primaryFrontend/top.html
{% extends '../base.html' %}
{% load static %}

{% block title %}Top Movies - YouTube Movies{% endblock title %}

{% block style %}
    <link rel="stylesheet" href="{% static './css/mvcards.css' %}">
    <link rel="stylesheet" href="{% static './css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static './css/owl.theme.default.min.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css" integrity="sha512-SzlrxWUlpfuzQ+pcUCosxcglQRNAq/DZjVsC0lE40xsADsfeQoEypE+enwcOiGjk/bSuGGKHEyjSoQ1zVisanQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
{% endblock style %}

{% block content %}
<main class="my-5 container-lg">
    <h1 class="pt-5 pb-3">Recommended Movies</h1>

    <!-- Big card here -->
    <div class="card my-4">
        <div class="row g-0">
            {% for m in rMovie %}
            {% if m.isRecommended %}
            <div class="col-md-4" style="width: 280px;">
                <img src="{{ m.poster}}" class="img-fluid rounded-start" alt="...">
            </div>
            <div class="col-md-8">
                <div class="card-body">
                    <h1 class="card-title">{{ m.movieName }}</h1>
                    <p class="card-text">{{ m.description }}</p>
                    <p class="card-text">Genres: {{ m.genre }}</p>
                    <p class="card-text">Rating: {{ m.rating }}</p>
                    <p class="card-text">Producer: {{ m.producer }}</p>
                    <a href="{% url 'moviePage' pk=m.pk %}" role="button" class="btn btn-danger">Watch</a>
                </div>
            </div>
            {% else %}
            <h3>No Recommended Movie </h3>
            {% endif %}
            {% endfor %}
        </div>
    </div>

    <!-- Carousel -->
    <div class="owl-carousel owl-theme">
        {% for movie in topMovies %}
        {% if movie.isTopTen %}
        <a class="card text-bg-dark mx-auto" href="{% url 'moviePage' pk=movie.pk %}">
            <img src="{{ movie.poster }}"
                class="card-img " alt="...">
            <div class="card-img-overlay d-flex flex-column">
                <h4 class="card-title">{{ movie.movieName}}</h4>
                <p class="card-text desc">{{ movie.description }}</p>
                <p class="card-text"><small>{{ movie.genre }}</small></p>
            </div>
        </a>
        {% else %}
        <h3>No Top Movies </h3>
        {% endif %}
        {% endfor %}
    </div>
    <div class="custom-nav my-3">
        <div class="owl-dots"></div> <!-- Navigation dots -->
        <div class="owl-nav">
            <button class="owl-prev"><i class="fas fa-chevron-left"></i></button> <!-- Prev button -->
            <button class="owl-next"><i class="fas fa-chevron-right"></i></button> <!-- Next button -->
        </div>
    </div>
</main>
{% endblock content %}

YT_Movies/YTM_app/templates/user/login.html
{% extends '../base.html' %}

{% block title %}Log In - YouTube Movies{% endblock title %}

{% block content %} 
<div class="container my-4">
    <div class="card">
        <div class="card-body">
            <h1>Log in</h1>
            <form method="post">
                {% csrf_token %}
                {{ form }}
                <button class="btn btn-danger">Login</button>
                <a href="{% url 'signupPage' %}">If no accaunt, link here</a>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

YT_Movies/YTM_app/templates/user/signup.html
{% extends '../base.html' %}

{% block title %}Sign Up - YouTube Movies{% endblock title %}

{% block content %} 
<div class="container my-4">
    <div class="card">
        <div class="card-body">
            <h1>Sign up</h1>
            <form method="post">
                {% csrf_token %}
                {{ form }}
                <button class="btn btn-danger">Signup</button>
                <a href="{% url 'loginPage' %}">If have account, link here</a>
            </form>
        </div>
    </div>
</div>
{% endblock content %}